site_name: LogFortress Docs
nav:
  - Home: index.md
  - Installation: installation.md
  - CLI: cli.md
  
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    primary: brown
  font:
    text: Open Sans
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.annotate

repo_url: https://github.com/williammadie/logfortress
repo_name: williammadie/logfortress

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences